<?php
$title = 'Login';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'index')));
$form->prepare();

	if(count($flashMessages)) : ?>
	<ul>
	    <?php foreach ($flashMessages as $msg) : ?>
	    <li><?php echo $msg; ?></li>
	    <?php endforeach; ?>
	</ul>
<?php 
	endif;

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();