<?php

$title = 'Edit wishtlist item';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'children',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('user'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('cost'));
echo $this->formRow($form->get('storeOrWebsite'));
echo $this->formRow($form->get('additionalInformation'));
echo $this->formRow($form->get('taken'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();