<?php
$title = 'Delete child';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to remove
    '<?php echo $this->escapeHtml($child->firstName); ?>'?
</p>
<?php
$url = $this->url('users', array(
    'action' => 'deleteChild',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $child->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>