<?php
$title = 'Edit user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('users', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('firstName'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('role'));
echo $this->formRow($form->get('family'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
<?php if($role < 3): ?>
<p>
	<a href="<?php echo $this->url('users', array('action' => 'addChild', 'id' => $this->id)); ?>">Add / Edit Children</a>
</p>
<?php if(count($children) > 0): ?>
<table class="table">
	<tr>
		<th>Children</th>
	</tr>
	<?php foreach($children as $key => $value): ?>
	<tr>
		<td><?php echo $value; ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php endif;
	endif; ?>